//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/04/26 - 19:49:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace ModernHelpDesk.Common.Models
{
    [DataContract()]
    public partial class Tickets
    {
        [DataMember()]
        public Int32 Id { get; set; }

        [DataMember()]
        public Int32 IssueId { get; set; }

        [DataMember()]
        public Int32 UserRequestId { get; set; }

        [DataMember()]
        public Int32 RequestDepartamentId { get; set; }

        [DataMember()]
        public Int32 DestinationDivisionId { get; set; }

        [DataMember()]
        public Int32 Estatus { get; set; }

        [DataMember()]
        public DateTime Fecha_Solicitud { get; set; }

        [DataMember()]
        public DateTime Fecha_Correcion { get; set; }

        [DataMember()]
        public DateTime Fecha_Modificacion { get; set; }

        [DataMember()]
        public Int32 OrganizacionId { get; set; }

        [DataMember()]
        public Int32 DEPARTAMENTOS_Id { get; set; }

        [DataMember()]
        public Int32 DIVISION_Id { get; set; }

        [DataMember()]
        public Int32 ESTATUS1_Id { get; set; }

        [DataMember()]
        public Int32 ISSUES_Id { get; set; }

        [DataMember()]
        public Int32 ORGANIZACION_Id { get; set; }

        [DataMember()]
        public Int32 USUARIOS_id { get; set; }

        public Tickets()
        {
        }

        public Tickets(Int32 id, Int32 issueId, Int32 userRequestId, Int32 requestDepartamentId, Int32 destinationDivisionId, Int32 estatus, DateTime fecha_Solicitud, DateTime fecha_Correcion, DateTime fecha_Modificacion, Int32 organizacionId, Int32 dEPARTAMENTOS_Id, Int32 dIVISION_Id, Int32 eSTATUS1_Id, Int32 iSSUES_Id, Int32 oRGANIZACION_Id, Int32 uSUARIOS_id)
        {
			this.Id = id;
			this.IssueId = issueId;
			this.UserRequestId = userRequestId;
			this.RequestDepartamentId = requestDepartamentId;
			this.DestinationDivisionId = destinationDivisionId;
			this.Estatus = estatus;
			this.Fecha_Solicitud = fecha_Solicitud;
			this.Fecha_Correcion = fecha_Correcion;
			this.Fecha_Modificacion = fecha_Modificacion;
			this.OrganizacionId = organizacionId;
			this.DEPARTAMENTOS_Id = dEPARTAMENTOS_Id;
			this.DIVISION_Id = dIVISION_Id;
			this.ESTATUS1_Id = eSTATUS1_Id;
			this.ISSUES_Id = iSSUES_Id;
			this.ORGANIZACION_Id = oRGANIZACION_Id;
			this.USUARIOS_id = uSUARIOS_id;
        }
    }
}
