//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernHelpDesk.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpDeskApfEntities : DbContext
    {
        public HelpDeskApfEntities()
            : base("name=HelpDeskApfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public DbSet<DIVISION> DIVISION { get; set; }
        public DbSet<ESTATUS> ESTATUS { get; set; }
        public DbSet<GRUPOS> GRUPOS { get; set; }
        public DbSet<ISSUES> ISSUES { get; set; }
        public DbSet<ORGANIZACION> ORGANIZACION { get; set; }
        public DbSet<PREGUNTAS> PREGUNTAS { get; set; }
        public DbSet<PRIORIDAD> PRIORIDAD { get; set; }
        public DbSet<TICKETS> TICKETS { get; set; }
        public DbSet<TICKETS_RESPUESTA> TICKETS_RESPUESTA { get; set; }
        public DbSet<USER_GROUPS> USER_GROUPS { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<USER_FOLLOWED_USER> USER_FOLLOWED_USER { get; set; }
    }
}
