//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernHelpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS_RESPUESTA
    {
        public int IdTickets { get; set; }
        public int IdPregunta { get; set; }
        public bool Respuesta { get; set; }
    }
}
