//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernHelpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int Id { get; set; }
        public int IssueId { get; set; }
        public int UserRequestId { get; set; }
        public int RequestDepartamentId { get; set; }
        public int DestinationDivisionId { get; set; }
        public int Estatus { get; set; }
        public System.DateTime Fecha_Solicitud { get; set; }
        public System.DateTime Fecha_Correcion { get; set; }
        public System.DateTime Fecha_Modificacion { get; set; }
        public int OrganizacionId { get; set; }
    
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        public virtual DIVISION DIVISION { get; set; }
        public virtual ESTATUS ESTATUS1 { get; set; }
        public virtual ISSUES ISSUES { get; set; }
        public virtual ORGANIZACION ORGANIZACION { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
