//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernHelpDesk.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_FOLLOWED_USER
    {
        public int UserID { get; set; }
        public int UserIdFollowed { get; set; }
        public System.DateTime Fecha_Creacion { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
